name: UiPath CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      # UiPath Orchestrator connection info - fill these
      UIPATH_ORCH_URL: "https://cloud.uipath.com/your-org/your-tenant"
      UIPATH_CLIENT_ID: ${{ secrets.APP_ID }}
      UIPATH_USER_KEY: ${{ secrets.UIPATH_CLIENT_ID }}
      UIPATH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
      UIPATH_ACCOUNT_LOGICAL_NAME: ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}
      UIPATH_ORG_UNIT: "Test"
      UIPATH_FOLDER: ${{ secrets.UIPATH_FOLDER_PATH }}
      DOTNET_ROOT: "C:\\Program Files\\dotnet"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install UiPath CLI
      shell: pwsh
      run: |
        dotnet tool install --global uipath.cli `
          --add-source "https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Official/nuget/v3/index.json" `
          --version 25.4.9239.19674

    - name: Publish UiPath project to Orchestrator
      shell: pwsh
      run: |
        # Add dotnet tools to PATH
        $env:PATH += ";" + $env:USERPROFILE + "\.dotnet\tools"

        # Publish the .nupkg (replace path to your package)
        uipcli project publish --package-path "./path/to/yourproject.nupkg" --folder "$env:UIPATH_FOLDER" --org-unit "$env:UIPATH_ORG_UNIT"

    - name: Start UiPath job in Orchestrator
      shell: pwsh
      run: |
        $env:PATH += ";" + $env:USERPROFILE + "\.dotnet\tools"

        # Start job (replace ProcessName with your actual process name)
        uipcli job start --process-name "YourProcessName" --folder "$env:UIPATH_FOLDER" --org-unit "$env:UIPATH_ORG_UNIT"
