name: UiPath Deploy and Run

on:
  push:
    branches:
      - main

jobs:
  deploy-and-run:
    runs-on: windows-latest

    env:
      UIPATH_ORCHESTRATOR_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      UIPATH_TENANT: ${{ secrets.UIPATH_TENANT }}
      UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      UIPATH_USER_KEY: ${{ secrets.UIPATH_USER_KEY }}
      UIPATH_ACCOUNT_LOGICAL_NAME: ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}
      UIPATH_FOLDER_LOGICAL_NAME: ${{ secrets.UIPATH_FOLDER_LOGICAL_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET CLI (if needed)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install UiPath CLI
        run: |
          dotnet tool install --global uipath.cli --add-source "https://uipath.visualstudio.com/Public.Feeds/_packaging/UiPath-Official/nuget/v3/index.json" --version 25.4.9239.19674
        shell: pwsh

      - name: Publish project to Orchestrator
        run: |
          uipcli project push \
            --path "." \
            --url $env:UIPATH_ORCHESTRATOR_URL \
            --clientId $env:UIPATH_CLIENT_ID \
            --userKey $env:UIPATH_USER_KEY \
            --accountLogicalName $env:UIPATH_ACCOUNT_LOGICAL_NAME \
            --tenantLogicalName $env:UIPATH_TENANT \
            --folder $env:UIPATH_FOLDER_PATH
        shell: pwsh

      - name: Trigger job in Orchestrator
        run: |
          uipcli job start \
            --process-name "Your_Process_Name_Here" \
            --url $env:UIPATH_ORCHESTRATOR_URL \
            --clientId $env:UIPATH_CLIENT_ID \
            --userKey $env:UIPATH_USER_KEY \
            --accountLogicalName $env:UIPATH_ACCOUNT_LOGICAL_NAME \
            --tenantLogicalName $env:UIPATH_TENANT \
            --folder $env:UIPATH_FOLDER_PATH
        shell: pwsh
