name: UiPath Publish to Orchestrator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-uipath:
    runs-on: windows-latest

    env:
      ORCH_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      ORCH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      ORCH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
      ORCH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
      PROJECT_PATH: ${{ secrets.UIPATH_FOLDER_PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet.config for UiPath CLI
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path ".nuget"
        Add-Content ".nuget/NuGet.Config" '<?xml version="1.0" encoding="utf-8"?>'
        Add-Content ".nuget/NuGet.Config" '<configuration>'
        Add-Content ".nuget/NuGet.Config" '  <packageSources>'
        Add-Content ".nuget/NuGet.Config" '    <add key="UiPath Dev" value="https://www.myget.org/F/uipath-dev/api/v3/index.json" />'
        Add-Content ".nuget/NuGet.Config" '  </packageSources>'
        Add-Content ".nuget/NuGet.Config" '</configuration>'

    - name: Install UiPath CLI using tool-path
      shell: pwsh
      run: |
        $toolPath = "$env:USERPROFILE\.dotnet-tools"
        dotnet tool install UiPath.CLI `
          --version 1.0.7985.19721 `
          --tool-path $toolPath `
          --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json
        echo "##[add-path]$toolPath"

    - name: Verify UiPath CLI version
      shell: pwsh
      run: |
        $env:PATH = "$env:USERPROFILE\.dotnet-tools;$env:PATH"
        uipath --version

    - name: Publish project to Orchestrator
      shell: pwsh
      run: |
        $env:PATH = "$env:USERPROFILE\.dotnet-tools;$env:PATH"
        uipath project push `
          --project-path "${{ env.PROJECT_PATH }}" `
          --orchestratorUrl "${{ env.ORCH_URL }}" `
          --clientId "${{ env.ORCH_CLIENT_ID }}" `
          --clientSecret "${{ env.ORCH_CLIENT_SECRET }}" `
          --tenant "${{ env.ORCH_TENANT }}"
