name: UiPath CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean tools folder
      shell: pwsh
      run: |
        if (Test-Path ./tools) {
          Remove-Item -Recurse -Force ./tools
        }

    - name: Setup tools folder path
      shell: pwsh
      run: echo "$PWD/tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install UiPath CLI locally
      shell: pwsh
      run: dotnet tool install UiPath.CLI --tool-path $PWD/tools --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json

    - name: Verify UiPath CLI installation
      shell: pwsh
      run: $toolsPath = "$PWD/tools"; & "$toolsPath\uipath.exe" --version
