name: UiPath CI Debug

on:
  push:
    branches:
      - '*'      # triggers on all branches
  pull_request:
    branches:
      - '*'      # triggers on all branches

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Show current branch (simple message)
      shell: pwsh
      run: Write-Host "Running UiPath CI workflow"

    - name: Clear NuGet cache
      shell: pwsh
      run: dotnet nuget locals all --clear

    - name: Install UiPath CLI globally
      shell: pwsh
      run: dotnet tool install --global UiPath.CLI --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json

    - name: Add dotnet global tools to PATH
      shell: pwsh
      run: Add-Content -Path $Env:GITHUB_PATH -Value 'C:\Users\runneradmin\.dotnet\tools'

    - name: Verify UiPath CLI installation
      shell: pwsh
      run: uipath --version
