name: UiPath Publish via Docker CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-uipath:
    runs-on: ubuntu-latest   # Use Ubuntu runner for Docker

    env:
      ORCH_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      ORCH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      ORCH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
      ORCH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
      PROJECT_PATH: ./TestAutomation  # Adjust as per your repo structure

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish UiPath project using Docker CLI
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/${{ env.PROJECT_PATH }}:/workspace \
          uipath/uipath-cli
