name: UiPath Publish to Orchestrator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-uipath:
    runs-on: windows-latest

    env:
      ORCH_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      ORCH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      ORCH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
      ORCH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
      PROJECT_PATH: ${{ secrets.UIPATH_FOLDER_PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up NuGet.config for UiPath CLI
      run: |
        mkdir .nuget
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <configuration>
          <packageSources>
            <add key=\"UiPath Dev\" value=\"https://www.myget.org/F/uipath-dev/api/v3/index.json\" />
          </packageSources>
        </configuration>" > .nuget/NuGet.Config

    - name: Install UiPath CLI tool manifest
      run: |
        dotnet new tool-manifest --force
        dotnet tool install UiPath.CLI --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json --version 1.0.0-preview-3 --ignore-failed-sources || true
        dotnet tool restore

    - name: Verify UiPath CLI version
      run: dotnet tool run uipath.cli --version

    - name: Publish to Orchestrator
      run: |
        dotnet tool run uipath.cli project push `
          --project-path "${{ env.PROJECT_PATH }}" `
          --orchestratorUrl "${{ env.ORCH_URL }}" `
          --clientId "${{ env.ORCH_CLIENT_ID }}" `
          --clientSecret "${{ env.ORCH_CLIENT_SECRET }}" `
          --tenant "${{ env.ORCH_TENANT }}"
