name: UiPath Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install UiPath CLI
        run: npm install -g @uipath/cli

      - name: Publish UiPath project to Orchestrator
        env:
          UIPATH_ORCH_URL: ${{ secrets.UIPATH_ORCH_URL }}
          UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
          UIPATH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
          UIPATH_TENANT_NAME: ${{ secrets.UIPATH_TENANT_NAME }}
        run: |
          uipath login --url $UIPATH_ORCH_URL --client-id $UIPATH_CLIENT_ID --client-secret $UIPATH_CLIENT_SECRET --tenant $UIPATH_TENANT_NAME
          uipath publish --path ./YourUiPathProjectFolder
