name: Publish UiPath Project to Orchestrator

on:
  push:
    branches:
      - main  # or your release branch

jobs:
  publish:
    runs-on: ubuntu-latest  # or windows-latest if you need UiPath CLI support on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET (if needed for UiPath CLI)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # match UiPath CLI requirements

      - name: Install UiPath CLI
        run: |
          dotnet tool install --global UiPath.Cli

      - name: Login to Orchestrator
        run: |
          uipath login --url ${{ secrets.UIPATH_ORCHESTRATOR_URL }} --tenant ${{ secrets.UIPATH_TENANT_NAME }} --client-id ${{ secrets.UIPATH_CLIENT_ID }} --client-secret ${{ secrets.UIPATH_CLIENT_SECRET }}

      - name: Publish project
        run: |
          uipath pack --output ./output
          uipath publish --path ./output/*.nupkg --folder ${{ secrets.UIPATH_FOLDER_PATH }}

      - name: Logout from Orchestrator
        run: uipath logout
