name: Publish UiPath Project to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download and unzip UiPath CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://download.uipath.com/cli/uipcli-latest-win.zip" -OutFile "uipcli.zip"
          Expand-Archive -Path "uipcli.zip" -DestinationPath "uipcli"
          echo "$PWD\\uipcli" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Authenticate to Orchestrator
        shell: pwsh
        run: |
          uipcli\uipcli.exe login `
            --client-id "${{ secrets.UIPATH_CLIENT_ID }}" `
            --user-key "${{ secrets.UIPATH_USER_KEY }}" `
            --url "${{ secrets.UIPATH_ORCHESTRATOR_URL }}" `
            --account-name "${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}" `
            --tenant "${{ secrets.UIPATH_TENANT }}"

      - name: Validate UiPath Project
        shell: pwsh
        run: |
          uipcli\uipcli.exe project validate --project-path .

      - name: Pack UiPath Project
        shell: pwsh
        run: |
          uipcli\uipcli.exe project pack --project-path . --output-path output

      - name: Publish Package to Orchestrator
        shell: pwsh
        run: |
          uipcli\uipcli.exe package push `
            --file-path "output\*.nupkg" `
            --folder "${{ secrets.UIPATH_FOLDER }}" `
            --force
