name: Run UiPath Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install UiPath CLI
      run: dotnet tool install -g UiPath.CLI

    - name: Run UiPath Test Set
      run: |
        uipcli test run \
          --orchestrator-url "${{ secrets.UIPATH_ORCHESTRATOR_URL }}" \
          --client-id "${{ secrets.UIPATH_CLIENT_ID }}" \
          --client-secret "${{ secrets.UIPATH_CLIENT_SECRET }}" \
          --account-logical-name "${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}" \
          --tenant-logical-name "${{ secrets.UIPATH_TENANT_NAME }}" \
          --folder-path "${{ secrets.UIPATH_FOLDER_PATH }}" \
          --test-set "${{ secrets.UIPATH_TESTSET_ID }}" \
          --format JUnit \
          --output junit-results.xml

    - name: Upload test results to Test Manager
      run: |
        uipcli test results upload \
          --file-path "junit-results.xml" \
          --format "JUnit" \
          --orchestrator-url "${{ secrets.UIPATH_ORCHESTRATOR_URL }}" \
          --client-id "${{ secrets.UIPATH_CLIENT_ID }}" \
          --client-secret "${{ secrets.UIPATH_CLIENT_SECRET }}" \
          --account-logical-name "${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}" \
          --tenant-logical-name "${{ secrets.UIPATH_TENANT_NAME }}" \
          --project-name "${{ secrets.UIPATH_TEST_MANAGER_PROJECT }}"
