name: Publish UiPath Project to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 👇 Install UiPath CLI via .NET Tool
      - name: Install UiPath CLI
        run: |
          dotnet new tool-manifest
          dotnet tool install uipcli

      # 👇 Authenticate to Orchestrator
      - name: Login to UiPath Orchestrator
        run: |
          dotnet tool run uipcli login `
            --client-id "${{ secrets.UIPATH_CLIENT_ID }}" `
            --user-key "${{ secrets.UIPATH_CLIENT_SECRET }}" `
            --url "${{ secrets.UIPATH_ORCHESTRATOR_URL }}" `
            --account-name "${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}" `
            --tenant "${{ secrets.UIPATH_TENANT_NAME }}"

      # 👇 Validate and Pack the UiPath Project
      - name: Validate and Pack Project
        run: |
          dotnet tool run uipcli project validate --project-path .
          dotnet tool run uipcli project pack --project-path . --output-path output

      # 👇 Publish to Orchestrator
      - name: Push Package to Orchestrator
        run: |
          dotnet tool run uipcli package push `
            --file-path "output\\*.nupkg" `
            --folder "${{ secrets.UIPATH_FOLDER_PATH }}" `
            --force
