name: Publish UiPath Project to Orchestrator

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  publish:
    runs-on: windows-latest

    env:
      PROJECT_PATH: './TestAutomation'
      UIPATH_ORCHESTRATOR_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      UIPATH_TENANT_NAME: ${{ secrets.UIPATH_TENANT_NAME }}
      UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      UIPATH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Publish UiPath project to Orchestrator
        shell: pwsh
        run: |
          dotnet tool run uipcli `
            project publish `
            --project-path $env:PROJECT_PATH `
            --output-path "$env:PROJECT_PATH/published" `
            --orchestrator-url $env:UIPATH_ORCHESTRATOR_URL `
            --tenant $env:UIPATH_TENANT_NAME `
            --client-id $env:UIPATH_CLIENT_ID `
            --client-secret $env:UIPATH_CLIENT_SECRET
