name: UiPath CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  uipath-ci:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up UiPath CLI
        run: |
          Invoke-WebRequest -Uri "https://download.uipath.com/cli/uipcli-latest-win.zip" -OutFile "uipcli.zip"
          Expand-Archive -Path "uipcli.zip" -DestinationPath "uipcli"
          echo "$PWD\\uipcli" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Authenticate with Orchestrator
        run: |
          uipcli login ^
            --client-id "${{ secrets.UIPATH_CLIENT_ID }}" ^
            --user-key "${{ secrets.UIPATH_CLIENT_SECRET }}" ^
            --url "${{ secrets.UIPATH_ORCHESTRATOR_URL }}" ^
            --account-name "${{ secrets.UIPATH_TENANT_NAME }}" ^
            --tenant "${{ secrets.UIPATH_TENANT_NAME }}"

      - name: Validate Project
        run: uipcli project validate --project-path .

      - name: Pack Project
        run: uipcli project pack --project-path . --output-path output

      - name: Publish Package to Orchestrator
        run: |
          uipcli package push ^
            --file-path "output\\*.nupkg" ^
            --folder "${{ secrets.UIPATH_FOLDER_PATH }}" ^
            --force

      # Optional: Deploy to a process
      # - name: Deploy Process
      #   run: |
      #     uipcli deploy ^
      #       --package-name "<your_package_name>" ^
      #       --process "<your_process_name>" ^
      #       --folder "${{ secrets.UIPATH_FOLDER }}"
