name: Upload UiPath Package

on:
  push:
    branches: [main]

env:
  UIPATH_ACCOUNT_LOGICAL_NAME: testbfsvyha
  UIPATH_TENANT: DefaultTenant
  UIPATH_ORCH_URL: https://cloud.uipath.com

jobs:
  upload-package:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Orchestrator and get access token
        id: auth
        shell: pwsh
        run: |
          $clientId = "21a6955b-2fbe-4cd4-8d71-4124dff739ce"
          $clientSecret = "1ljhMu`$Db!6boY6W"  # Escape $ for PowerShell
          $scope = "OR.Jobs"
          
          $body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"
          
          try {
              $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
                  -Method Post `
                  -Body $body `
                  -ContentType "application/x-www-form-urlencoded" `
                  -ErrorAction Stop

              Write-Output "Access token received"
              echo "::set-output name=token::$($response.access_token)"
          }
          catch {
              Write-Error "Authentication failed: $_"
              exit 1
          }

      - name: Upload package to Orchestrator
        shell: pwsh
        env:
          UIPATH_ORCH_URL: https://cloud.uipath.com
          ORCH_TOKEN: ${{ steps.auth.outputs.token }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          $packagePath = "$env:GITHUB_WORKSPACE\path\to\your\package.nupkg"
          if (-Not (Test-Path $packagePath)) {
            Write-Error "Package file not found at $packagePath"
            exit 1
          }

          Write-Output "Uploading package: $packagePath"
          Invoke-RestMethod -Uri "$env:UIPATH_ORCH_URL/odata/Packages/UiPath.Server.Configuration.OData.UploadPackage" `
            -Method Post `
            -Headers @{ Authorization = "Bearer $env:ORCH_TOKEN" } `
            -InFile $packagePath `
            -ContentType "application/octet-stream"

          Write-Output "Package upload completed"
