name: Build & Upload UiPath Package

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download UiPath CLI
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest -Uri "https://github.com/UiPath/uipathcli/releases/latest/download/uipathcli-windows-amd64.zip" -OutFile "uipathcli.zip"
          Expand-Archive -Path "uipathcli.zip" -DestinationPath "uipathcli"

      - name: Pack UiPath project
        shell: pwsh
        run: |
          $projectPath = "$env:GITHUB_WORKSPACE\project.json"
          $outputFolder = "$env:GITHUB_WORKSPACE\output"
          New-Item -ItemType Directory -Path $outputFolder -Force | Out-Null
          & "$env:GITHUB_WORKSPACE\uipathcli\uipcli.exe" project pack "$projectPath" --output "$outputFolder"

      - name: Get latest nupkg path
        id: get-package
        shell: pwsh
        run: |
          $nupkg = Get-ChildItem -Path "$env:GITHUB_WORKSPACE\output" -Filter *.nupkg | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          echo "PACKAGE_PATH=$($nupkg.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Authenticate with UiPath Orchestrator
        id: auth
        shell: pwsh
        run: |
          $clientId = "21a6955b-2fbe-4cd4-8d71-4124dff739ce"
          $clientSecret = "1ljhMu$Db!6boY6W"
          $accountLogicalName = "testbfsvyha"
          $tenant = "DefaultTenant"
          $orchUrl = "https://cloud.uipath.com"
          $scope = "OR.Assets OR.Jobs OR.Machines OR.Execution OR.Folders"
          $body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"
          $response = Invoke-RestMethod -Uri "$orchUrl/identity_/connect/token" `
            -Method Post `
            -Body $body `
            -ContentType "application/x-www-form-urlencoded"
          echo "ORCH_TOKEN=$($response.access_token)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ORCH_URL=$orchUrl" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ACCOUNT_NAME=$accountLogicalName" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TENANT=$tenant" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload Package to Orchestrator
        shell: pwsh
        run: |
          Write-Host "Uploading: $env:PACKAGE_PATH"
          Invoke-RestMethod -Uri "$env:ORCH_URL/$env:ACCOUNT_NAME/$env:TENANT/odata/Packages/UiPath.Server.Configuration.OData.UploadPackage" `
            -Method Post `
            -Headers @{ Authorization = "Bearer $env:ORCH_TOKEN" } `
            -InFile $env:PACKAGE_PATH `
            -ContentType "application/octet-stream"
          Write-Host "✅ Package uploaded successfully"
