name: Publish UiPath Package to Orchestrator

on:
  push:
    branches: [main]

env:
  UIPATH_CLIENT_ID: 21a6955b-2fbe-4cd4-8d71-4124dff739ce
  UIPATH_CLIENT_SECRET: 1ljhMu$Db!6boY6W
  UIPATH_ACCOUNT_LOGICAL_NAME: testbfsvyha
  UIPATH_TENANT: DefaultTenant
  UIPATH_ORCH_URL: https://cloud.uipath.com

jobs:
  publish-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find .nupkg package
        id: find-package
        shell: pwsh
        run: |
          $package = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse -Filter *.nupkg | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $package) { throw "No .nupkg package found!" }
          echo "PACKAGE_PATH=$($package.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Authenticate with UiPath Orchestrator
        id: auth
        shell: pwsh
        run: |
          $clientId = "21a6955b-2fbe-4cd4-8d71-4124dff739ce"
          $clientSecret = "1ljhMu$Db!6boY6W"
          $scope = "OR.Assets OR.Jobs OR.Machines OR.Execution OR.Folders"
          $body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"
          $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
            -Method Post `
            -Body $body `
            -ContentType "application/x-www-form-urlencoded"
          echo "ORCH_TOKEN=$($response.access_token)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload package to Orchestrator
        shell: pwsh
        run: |
          Write-Host "Uploading package: $env:PACKAGE_PATH"
          Invoke-RestMethod -Uri "https://cloud.uipath.com/testbfsvyha/DefaultTenant/odata/Packages/UiPath.Server.Configuration.OData.UploadPackage" `
            -Method Post `
            -Headers @{ Authorization = "Bearer $env:ORCH_TOKEN" } `
            -InFile $env:PACKAGE_PATH `
            -ContentType "application/octet-stream"
          Write-Host "✅ Package uploaded successfully"
