name: Publish UiPath Project

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dotnet tools folder and add to PATH
        shell: pwsh
        run: |
          $toolsPath = "$env:USERPROFILE\.dotnet\tools"
          if (-Not (Test-Path $toolsPath)) {
            New-Item -ItemType Directory -Path $toolsPath | Out-Null
          }
          Add-Content -Path $env:GITHUB_PATH -Value $toolsPath

      - name: Install UiPath CLI locally
        shell: pwsh
        run: dotnet tool install UiPath.CLI --tool-path $env:USERPROFILE\.dotnet\tools --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json

      - name: Publish project to Orchestrator using Client ID auth
        shell: pwsh
        env:
          UIPATH_ORCH_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
          UIPATH_ORCH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
          UIPATH_ORCH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
          UIPATH_ORCH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
        run: |
          uipath login --url $env:UIPATH_ORCHESTRATOR_URL `
                       --client-id $env:UIPATH_CLIENT_ID `
                       --client-secret $env:UIPATH_CLIENT_SECRET `
                       --tenant $env:UIPATH_TENANT_NAME

          uipath publish --path . --packageVersion "1.0.${{ github.run_number }}"

          uipath logout
