name: UiPath Publish to Orchestrator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-uipath:
    runs-on: windows-latest

    env:
      ORCH_URL: ${{ secrets.UIPATH_ORCHESTRATOR_URL }}
      ORCH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
      ORCH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
      ORCH_TENANT: ${{ secrets.UIPATH_TENANT_NAME }}
      PROJECT_PATH: ${{ secrets.UIPATH_FOLDER_PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install UiPath CLI globally
      run: |
        dotnet tool install --global UiPath.CLI --add-source https://www.myget.org/F/uipath-dev/api/v3/index.json
        echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Check UiPath CLI version
      run: uipath --version

    - name: Publish to Orchestrator
      run: |
        uipath project push `
          --project-path "${{ env.PROJECT_PATH }}" `
          --orchestratorUrl "${{ env.ORCH_URL }}" `
          --clientId "${{ env.ORCH_CLIENT_ID }}" `
          --clientSecret "${{ env.ORCH_CLIENT_SECRET }}" `
          --tenant "${{ env.ORCH_TENANT }}"
