name: Publish UiPath Project to Orchestrator

on:
  push:
    branches:
      - main

jobs:
  publish-uipath-package:
    runs-on: windows-latest  # Required for UiPath CLI
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET (for UiPath CLI)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install UiPath CLI
        run: dotnet tool install --global UiPath.CLI

      - name: Authenticate to Orchestrator
        run: |
          uipcli config set -a cloud \
            --account-name "${{ secrets.UIPATH_ACCOUNT_NAME }}" \
            --client-id "${{ secrets.UIPATH_CLIENT_ID }}" \
            --user-key "${{ secrets.UIPATH_CLIENT_SECRET }}" \
            --service "${{ secrets.UIPATH_TENANT_NAME }}"

      - name: Publish Package to Orchestrator
        run: |
          uipcli project publish \
            --path . \
            --output-folder ./output \
            --project-version 1.0.$GITHUB_RUN_NUMBER \
            --force

      - name: Upload Package to Orchestrator
        run: |
          uipcli package push \
            --file ./output/*.nupkg \
            --folder "${{ secrets.UIPATH_FOLDER_PATH }}"
