name: Build, Publish, and Run UiPath Process

on:
  push:
    branches:
      - main   # or your main branch

jobs:
  build_publish_run:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET (for future usage if needed)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build UiPath package
      shell: pwsh
      run: |
        # Define project path and output folder
        $projectPath = "C:\Users\Saiteja.Indarapu\OneDrive - Elemica, Inc\Desktop\TestAutomationProject"  # path to your UiPath project folder
        $outputPath = "C:\Users\Saiteja.Indarapu\OneDrive - Elemica, Inc\Desktop\TestAutomationProject"    # output to the same folder
        
        # Pack the project using UiRobot.exe (adjust path if needed)
        & "C:\Program Files\UiPath\Studio\UiRobot.exe" pack --source $projectPath --output $outputPath --no-versioning
        
        # List the generated nupkg files
        Get-ChildItem -Path $outputPath -Filter *.nupkg

    - name: Upload package to Orchestrator
      id: upload
      shell: pwsh
      env:
        UIPATH_CLIENT_ID: "21a6955b-2fbe-4cd4-8d71-4124dff739ce"  # Your real Client ID
        UIPATH_CLIENT_SECRET: "1ljhMu`$Db!6boY6W"  # Your real Client Secret (escaped $ for PowerShell)
        UIPATH_ACCOUNT_LOGICAL_NAME: "testbfsvyha"  # Your account logical name
        UIPATH_TENANT: "DefaultTenant"  # Your tenant name
        UIPATH_FOLDER: "Shared"  # Your folder in Orchestrator
      run: |
        # Step 1: Get Auth Token
        $clientId = $env:UIPATH_CLIENT_ID.Trim()
        $clientSecret = $env:UIPATH_CLIENT_SECRET -replace '\$', '`$'
        $scope = "OR.Jobs"
        
        $body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"
        
        $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
            -Method Post `
            -Body $body `
            -ContentType "application/x-www-form-urlencoded"
        
        $accessToken = $response.access_token
        Write-Host "::add-mask::$accessToken"
        echo "token=$accessToken" >> $env:GITHUB_OUTPUT
        
        # Step 2: Upload .nupkg file
        $packagePath = "C:\Users\Saiteja.Indarapu\OneDrive - Elemica, Inc\Desktop\TestAutomationProject\TestAutomationProject.1.0.202484824.nupkg"

        if (!(Test-Path $packagePath)) {
          Write-Error "Package not found at path: $packagePath"
          exit 1
        }

        $uploadUrl = "https://cloud.uipath.com/$($env:UIPATH_ACCOUNT_LOGICAL_NAME)/$($env:UIPATH_TENANT)/odata/Processes/UiPath.Server.Configuration.OData.UploadPackage"

        $form = @{
          file = Get-Item $packagePath
          folderPath = $env:UIPATH_FOLDER
          overwriteExistingPackage = $true
        }

        Invoke-RestMethod -Uri $uploadUrl `
          -Headers @{ Authorization = "Bearer $accessToken" } `
          -Method Post `
          -Form $form

        Write-Host "Package uploaded successfully"

    - name: Start job in Orchestrator (optional)
      shell: pwsh
      env:
        UIPATH_CLIENT_ID: "21a6955b-2fbe-4cd4-8d71-4124dff739ce"  # Your real Client ID
        UIPATH_CLIENT_SECRET: "1ljhMu`$Db!6boY6W"  # Your real Client Secret (escaped $ for PowerShell)
        UIPATH_ACCOUNT_LOGICAL_NAME: "testbfsvyha"  # Your account logical name
        UIPATH_TENANT: "DefaultTenant"  # Your tenant name
        UIPATH_FOLDER: "Shared"  # Your folder in Orchestrator
      run: |
        # Get Auth Token (same as above)
        $body = @{
          grant_type = "refresh_token"
          client_id = $env:UIPATH_CLIENT_ID
          refresh_token = $env:UIPATH_USER_KEY
          scope = "OR.Jobs"
        } | ConvertTo-Json

        $authResponse = Invoke-RestMethod -Method Post -Uri "https://account.uipath.com/oauth/token" `
          -Headers @{ "Content-Type" = "application/json" } `
          -Body $body

        $accessToken = $authResponse.access_token

        # Fetch Process key (ProcessName should match your published process)
        $processName = "TestAutomationProject" 

        $processesUrl = "https://cloud.uipath.com/$($env:UIPATH_ACCOUNT_LOGICAL_NAME)/$($env:UIPATH_TENANT)/odata/Processes?\$filter=Name eq '$processName'"

        $processesResponse = Invoke-RestMethod -Uri $processesUrl -Headers @{ Authorization = "Bearer $accessToken" }

        if ($processesResponse.value.Count -eq 0) {
          Write-Error "Process '$processName' not found in Orchestrator"
          exit 1
        }

        $processKey = $processesResponse.value[0].Key

        # Start Job
        $startJobUrl = "https://cloud.uipath.com/$($env:UIPATH_ACCOUNT_LOGICAL_NAME)/$($env:UIPATH_TENANT)/odata/Jobs/UiPath.Server.Configuration.OData.StartJobs"

        $jobBody = @{
          startInfo = @{
            ReleaseKey = $processKey
            Strategy = "All" # or "Specific" or "JobsCount"
            # RobotIds = @() # Optional
            # NoOfRobots = 0 # Optional
            # InputArguments = "{}" # Optional JSON string
            # Source = "Manual" # Optional
          }
        } | ConvertTo-Json -Depth 10

        Invoke-RestMethod -Uri $startJobUrl -Headers @{ Authorization = "Bearer $accessToken" } -Method Post -Body $jobBody -ContentType "application/json"

        Write-Host "Job started successfully"
