name: Build, Publish and Run UiPath Process

on:
  push:
    branches:
      - main

jobs:
  build_publish_run:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build UiPath project (optional)
      run: |
        echo "Add UiPath Studio CLI build commands here if needed"

    - name: Request OAuth token via Client Credentials
      shell: pwsh
      id: get_token
      run: |
        $clientId = "21a6955b-2fbe-4cd4-8d71-4124dff739ce"
        $clientSecret = "1ljhMu`$Db!6boY6W"  # Escaped $ with backtick
        $scope = "OR.Jobs"

        # Create the form-urlencoded body
        $body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"

        # Request token
        $response = Invoke-RestMethod -Uri "https://cloud.uipath.com/identity_/connect/token" `
            -Method Post `
            -Body $body `
            -ContentType "application/x-www-form-urlencoded"

        # Output token and save to GitHub Actions output
        Write-Host "::add-mask::$($response.access_token)"
        echo "token=$($response.access_token)" >> $env:GITHUB_OUTPUT

    - name: Upload package to Orchestrator
      shell: pwsh
      env:
        ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
        UIPATH_ACCOUNT_LOGICAL_NAME: ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}
        UIPATH_TENANT: ${{ secrets.UIPATH_TENANT }}
        UIPATH_FOLDER: ${{ secrets.UIPATH_FOLDER }}
      run: |
        $packagePath = "TestAutomationProject.1.0.202484824.nupkg"
        if (!(Test-Path $packagePath)) {
          Write-Error "Package not found: $packagePath"
          exit 1
        }

        $uploadUrl = "https://cloud.uipath.com/$env:UIPATH_ACCOUNT_LOGICAL_NAME/$env:UIPATH_TENANT/odata/Processes/UiPath.Server.Configuration.OData.UploadPackage"

        $form = @{
          file = Get-Item $packagePath
          folderPath = $env:UIPATH_FOLDER
          overwriteExistingPackage = $true
        }

        Invoke-RestMethod -Uri $uploadUrl `
          -Headers @{ Authorization = "Bearer $env:ACCESS_TOKEN" } `
          -Method Post `
          -Form $form

        Write-Host "Package uploaded successfully"

    - name: Start job in Orchestrator
      shell: pwsh
      env:
        ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
        UIPATH_ACCOUNT_LOGICAL_NAME: ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}
        UIPATH_TENANT: ${{ secrets.UIPATH_TENANT }}
        UIPATH_FOLDER: ${{ secrets.UIPATH_FOLDER }}
      run: |
        $processName = "TestAutomationProject"

        $processesUrl = "https://cloud.uipath.com/$env:UIPATH_ACCOUNT_LOGICAL_NAME/$env:UIPATH_TENANT/odata/Processes?\$filter=Name eq '$processName'"

        $processesResponse = Invoke-RestMethod -Uri $processesUrl -Headers @{ Authorization = "Bearer $env:ACCESS_TOKEN" }

        if ($processesResponse.value.Count -eq 0) {
          Write-Error "Process '$processName' not found"
          exit 1
        }

        $processKey = $processesResponse.value[0].Key

        $startJobUrl = "https://cloud.uipath.com/$env:UIPATH_ACCOUNT_LOGICAL_NAME/$env:UIPATH_TENANT/odata/Jobs/UiPath.Server.Configuration.OData.StartJobs"

        $jobBody = @{
          startInfo = @{
            ReleaseKey = $processKey
            Strategy = "All"
          }
        } | ConvertTo-Json -Depth 10

        Invoke-RestMethod -Uri $startJobUrl -Headers @{ Authorization = "Bearer $env:ACCESS_TOKEN" } -Method Post -Body $jobBody -ContentType "application/json"

        Write-Host "Job started successfully"
